### ISSUE TITLE
How do we contribute to this site?

### ISSUE THREAD

**Issue by gep13** [appveyor/website#1]
Would be more than happy to help out here, where and when I can, but I think we need to get some guidance on how to get started.

I would assume that the preference is that any changes are tested locally before submitting as a pull request, so can we get some instructions on what is required to host and run the site locally?

You say it's based on Jekyll, but is there any special configuration required to get it up and running?

Thanks!

**Comment by gep13** [comment]
@FeodorFitsner just wanted to follow up with this.  Did you add this somewhere?

Thanks!

**Comment by FeodorFitsner** [comment]
It's really easy - the site is extremely simple without any dependencies or DB. You could setup it in minutes in IIS Manager or use IIS Express.

**Comment by gep13** [comment]
Ah, just looking again at source code, looks like things have changed since I last looked at it.  Looks much simpler now.

Thanks!
