### ISSUE TITLE
add the Win32 platform

### ISSUE THREAD

**Issue by mrexodia** [appveyor/website#111]
Hello, currently the BUILD section provides `Any CPU`, `x86`, `x64` and `ARM` but native projects usually have the platform name `Win32` instead of `x86` (x86 is used for managed projects).

It's not much of a hassle because it's easy to write a custom build script, but I think it's a good addition.

**Comment by XhmikosR** [comment]
@FeodorFitsner: this is related to the ci repo, not the website one, correct? If so, close the issue please.
