### ISSUE TITLE
Pushing to remote Git repository from a build doesn't work

### ISSUE THREAD

**Issue by joelself** [appveyor/website#114]
The page Pushing to remote Git repository from a build: https://github.com/appveyor/website/blob/master/NJekyll/site/docs/how-to/git-push.md doesn't work. At the end of the build I get

``` shell
git config --global credential.helper store
Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
git config --global user.email "name@emailprovider.com"
git config --global user.name "First Last"
git commit ...
fatal: Not a git repository (or any of the parent directories): .git
Command exited with code 128
```

**Comment by FeodorFitsner** [comment]
Could you please drop your appveyor.yml (with sensitive data removed)?

**Comment by joelself** [comment]
1. That's only a tiny snippet of an appveyor.yml (one that I got from your help page)
2. It's from a public github project so it's all public and readily viewable anyways
3. I did scrub the "sensitive" (public) data. My name isn't actually "First Last" and my email is not "name@emailprovider.com"

The other than the fake name and email the rest is straight from the help doc.

Also I figured out how to fix it, though I don't know if it's the the really correct way to do it:

```PowerShell
environment:
  access_token:
    secure: cUFRT/gTMFUL6JvjnVcEZ89q3W2k7YQRtqfQhjlsZ6oigK3cyurRIl3QZBRl4Vgc
on_success:
  - git config --global credential.helper store
  - git config --global push.default matching
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "notareal@emailprovider.com"
  - git config --global user.name "Not My Name"
  - git add -A *.zip *.dll
  - git commit -m "Adding newly built binaries for release[ci skip]"
  - git push origin
```
And yes the name, email and access_token are fake.

**Comment by joelself** [comment]
Ok, I actually checked the repository and the files are all still a month old. It looks like it's succeeding, but where is it pushing to? Do I need to specify a custom checkout command and then in on_success add my repository as a remote and specifically push to the repository I added?

**Comment by FeodorFitsner** [comment]
Try calling `git status` after `git add` command to see what was added.

**Comment by FeodorFitsner** [comment]
I'm just wondering why would you need pushing produced DLLs and executables back to repository?

**Comment by joelself** [comment]
That's where I was storing releases so people don't have to download and
build the project from sources.

On Fri, Jan 8, 2016 at 2:56 PM, Feodor Fitsner <notifications@github.com>
wrote:

> I'm just wondering why would you need pushing produced DLLs and
> executables back to repository?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appveyor/website/issues/114#issuecomment-170139115>.
>



-- 

Thanks,
Joel

**Comment by FeodorFitsner** [comment]
Why not pushing them to repository Releases then: http://www.appveyor.com/docs/deployment/github? This is a "standard" way of distributing releases.

**Comment by joelself** [comment]
Yeah that's what I do now.

On Fri, Jan 8, 2016 at 3:01 PM, Feodor Fitsner <notifications@github.com>
wrote:

> Why not pushing them to repository Releases then:
> http://www.appveyor.com/docs/deployment/github? This is a "standard" way
> of distributing releases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appveyor/website/issues/114#issuecomment-170140161>.
>



-- 

Thanks,
Joel

**Comment by XhmikosR** [comment]
@FeodorFitsner: can we close this since it's not related to the website?
