### ISSUE TITLE
Https config could use some improvements

### ISSUE THREAD

**Issue by 304NotModified** [appveyor/website#118]
The config of ci.appveyor.com could use some improvements. RC4 is deprecated a long time ago. On www.appveyor.com it is already being removed. 

![image](https://cloud.githubusercontent.com/assets/5808377/13192271/77acc6aa-d76a-11e5-8ae9-a129de85616b.png)

![image](https://cloud.githubusercontent.com/assets/5808377/13192352/3f6c3da6-d76b-11e5-944e-3400eb05d6f0.png)

https://www.ssllabs.com/ssltest/analyze.html?d=ci.appveyor.com

---

Maybe you should also replace the SSL of 	www.appveyor.com  with the wildcard (e.g. on ci.appveyor.com), as 	www.appveyor.com has still as SHA1 in the chain. The browser will remove the SHA1 support in 2016-2017

![image](https://cloud.githubusercontent.com/assets/5808377/13192338/15e8e894-d76b-11e5-8e12-8d9ef21e1971.png)

https://www.ssllabs.com/ssltest/analyze.html?d=appveyor.com

**Comment by FeodorFitsner** [comment]
Wildcard won't work as we need a cert for both www and naked domains. Maybe we just need more expensive cert - do you have any suggestions?

**Comment by 304NotModified** [comment]
Ow indeed, you can't use wildcards if naked domains are used. 

My experience is that certificates aren't expensive, also not when asking for full SHA2 chain (to be clear - the root can stay SHA1)

**Comment by 304NotModified** [comment]
Maybe you can ask for a (free) replacement. It's nonsense the give a SHA2 cert with a SHA1 chain. 

When the whole thing for SHA2 was in the news, we got for all the certificates a free SHA2 replacement. (that was at Comodo)

**Comment by FeodorFitsner** [comment]
Nice, thanks for the link!

**Comment by XhmikosR** [comment]
Wildcard certificates work for both `www` and naked domains.

I have a fairly good experience with this, and I can help set this up along with other things like HSTS, CSP, expires headers, etc.

![2016-07-26_10-45-54](https://cloud.githubusercontent.com/assets/349621/17129884/5efee2d4-531e-11e6-8c00-0d266d6105f7.png)

**Comment by 304NotModified** [comment]
> Wildcard certificates work for both www and naked domains

You mean, "Wildcard certificates **could** work for both www and naked domains". The naked domain should be listed as alternative name. 

But I see the *.appveyor.com has this alternative name:
![image](https://cloud.githubusercontent.com/assets/5808377/17131174/8b418a4c-531c-11e6-8c75-8d18bc2a8f97.png)



Is see this is still an issue:

![image](https://cloud.githubusercontent.com/assets/5808377/17131236/e5b75128-531c-11e6-8cd6-5fa57aba194d.png)
https://www.ssllabs.com/ssltest/analyze.html?d=appveyor.com

while ci.appveyor.com has the correct wildcard cert:
![image](https://cloud.githubusercontent.com/assets/5808377/17131259/049d8a58-531d-11e6-97ee-d2c8f342352f.png)


https://www.ssllabs.com/ssltest/analyze.html?d=ci.appveyor.com

 so the 2nd issue is really issue to fix:

- replace the cert of appveyor.com (SHA1) with the wildcard cert from ci.appveyor.com (SHA256)

could this be done in a short term @FeodorFitsner ?

**Comment by XhmikosR** [comment]
They all work just fine. You just need one person who knows what they're doing.

**Comment by XhmikosR** [comment]
This issue is no longer valid.

For the other suggestions please make separate issues for each one.

@FeodorFitsner: I suggest we close this for now.

**Comment by XhmikosR** [comment]
@FeodorFitsner: please consider closing this. Generally, we can't tweak the Azure SSL Cipher suite. Plus now, they have updated it to a more modern one.
