### ISSUE TITLE
Linking GitHub fails to sync primary email

### ISSUE THREAD

**Issue by asimpletune** [appveyor/website#140]
I linked my GH account to appveyor and the email address it sync'd was my college email address from years back when I first made my GH account, and a different email address is my "primary" email on GH. 

I think it would be expected for appveyor to link the primary address, rather than the oldest.

**Comment by FeodorFitsner** [comment]
I've just double-checked the code AppVeyor uses to get that email and it indeed takes the first one with `primary: true`: https://developer.github.com/v3/users/emails/#list-email-addresses-for-a-user

Try calling that API method to see what you get there (if you didn't change primary email already).

**Comment by asimpletune** [comment]
I already changed my emails unfortunately. Could it be a problem on GitHub's end then? Through the UI you can only have 1 primary I believe, so if there are multiple emails with primary: true, then that'd be a problem.

**Comment by XhmikosR** [comment]
This is not an issue with the website. Can we close this @FeodorFitsner ?
