### ISSUE TITLE
Add a redirect for 404.html

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/website#169]
And make sure the response code is 404 and not 200...

**Comment by FeodorFitsner** [comment]
Looks like the only way to do custom 404 page returning 404 status code would be having server-side logic in this page changing response status code, like here: http://stackoverflow.com/questions/347281/asp-net-custom-404-returning-200-ok-instead-of-404-not-found

The page can be named as `404.aspx` and there would be just a single line changing response status code.
