### ISSUE TITLE
Add RSS feed link/button

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/website#183]
Since we have an RSS feed for posts we should add it in frontend somewhere.

**Comment by XhmikosR** [comment]
@FeodorFitsner: where would you like the RSS feed link? Footer left, right? With image, without?

**Comment by FeodorFitsner** [comment]
Bottom without image?

**Comment by XhmikosR** [comment]
So you mean a simple link? I find icons much better for user experience...
