### ISSUE TITLE
Filtering - could I filter SCHEDULED_BUILD and COMMIT_AUTHOR at the same time?

### ISSUE THREAD

**Issue by hellosnow** [appveyor/website#214]
I've read through the documentation [Skip commits](https://www.appveyor.com/docs/how-to/filtering-commits/#skip-commits-1) , `skip_commits` is a good choice for filtering, but my scenario is to trigger CI when both:
1. When it's not scheduled job.
2. When it's not commit by specific user.

@FeodorFitsner, could it be implemented by specific commands? If not, is it the only way that I write the scripts in appveyor.yml to reuse environment variables such as `APPVEYOR_REPO_COMMIT_AUTHOR` and `APPVEYOR_SCHEDULED_BUILD`?

**Comment by FeodorFitsner** [comment]
I'm not sure why would you need to do something about "When it's not scheduled job" condition? Just don't setup scheduled job and it won't trigger a build, no?

**Comment by hellosnow** [comment]
We have both scheduled job and webhook monitoring, and have different conditions...

**Comment by FeodorFitsner** [comment]
Then you should check environment variables as you described in original post.

**Comment by hellosnow** [comment]
Thanks I'll reuse these 2 environment variables, close the issue now.

**Comment by hellosnow** [comment]
@FeodorFitsner sorry for one more question, is there a command to quit whole build in "before_build" or "build_script" if in some specific condition?

**Comment by FeodorFitsner** [comment]
you can use condition, like:

```yaml
build_script:
- ps: if($env:some_variable -eq 'A') { .\do-this.ps1 }
```

or

```yaml
build_script:
- IF "%SOME_VARIABLE%"=="A" do-that.cmd
```

**Comment by hellosnow** [comment]
Yes this is what I'm planning to do, if no `quit` whole CI command. Thanks anyway!
