### ISSUE TITLE
SVG icon

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/website#235]
So, it would be nice if we could switch to SVG icon for the toolbar logo and also regenerate favicons from the SVG one.

@dupstudio: can you make this https://github.com/appveyor/website/blob/master/src/assets/img/appveyor-logo-256.png as an SVG and when/if you have some time https://github.com/appveyor/website/blob/master/src/assets/img/logo-2x.png?

**Comment by dupstudio** [comment]
here is the logo:
[blob_logo.zip](https://github.com/appveyor/website/files/694668/blob_logo.zip)

**Comment by XhmikosR** [comment]
@dupstudio: it seems your SVG icon doesn't have the exact same background color?

The old one seems to be `#08a8ec` and yours `#35abe1`.

**Comment by dupstudio** [comment]
[blob_logo.zip](https://github.com/appveyor/website/files/696699/blob_logo.zip)
Check this i think is ok now..

**Comment by XhmikosR** [comment]
@dupstudio; I still notice a difference in the blue color... Please see the attached screenshot.

![compare](https://cloud.githubusercontent.com/assets/349621/21815124/3eda2c32-d764-11e6-8ed4-24d3aa1d3bc7.png)

**Comment by dupstudio** [comment]
[blob_logo.zip](https://github.com/appveyor/website/files/696784/blob_logo.zip)
is this ok ?

**Comment by XhmikosR** [comment]
The new one is still a little darker.

**Comment by XhmikosR** [comment]
@FeodorFitsner: what's the official hex color for the brand? Also, I don't suppose you have somewhere the vector icons?

**Comment by FeodorFitsner** [comment]
There is no official color, but take `#09A9ED`. Vector logo attached.
[appveyor-logo.zip](https://github.com/appveyor/website/files/709692/appveyor-logo.zip)

**Comment by XhmikosR** [comment]
Can one of you export it to SVG?

**Comment by FeodorFitsner** [comment]
Here you go: 
[appveyor-logo-svg.zip](https://github.com/appveyor/website/files/712994/appveyor-logo-svg.zip)

**Comment by XhmikosR** [comment]
@FeodorFitsner: I don't suppose you have the logo only without the letters too?

**Comment by FeodorFitsner** [comment]
[appveyor-logo-optimized.zip](https://github.com/appveyor/website/files/714738/appveyor-logo-optimized.zip)

**Comment by XhmikosR** [comment]
All right, we're almost there :)

Can you make the plain logo with white in the middle and not transparent? Around it, you can leave it transparent.

**Comment by XhmikosR** [comment]
@FeodorFitsner: ^^

**Comment by FeodorFitsner** [comment]
Here it is: [appveyor-logo-white-bkg.zip](https://github.com/appveyor/website/files/756662/appveyor-logo-white-bkg.zip)

**Comment by XhmikosR** [comment]
@FeodorFitsner: thanks! Now we are set with favicons.

About the navbar logo, the one you uploaded above has "AppVeyor" with blue color instead of white. Is this intentional?
