### ISSUE TITLE
Update Node JS Documentation Page?

### ISSUE THREAD

**Issue by kevinvangelder** [appveyor/website#237]
https://github.com/appveyor/website/blob/master/src/docs/lang/nodejs-iojs.md

This appears to be excessively out of date. The current version of Node JS is `6.9.4` and the documentation referencing `0.11` and `1.0` had me questioning my sanity.

**Comment by FeodorFitsner** [comment]
Fair enough! The page has been updated: https://www.appveyor.com/docs/lang/nodejs-iojs/

**Comment by kevinvangelder** [comment]
MUCH better! Thanks!
