### ISSUE TITLE
Replace testimonials with a Twitter collection

### ISSUE THREAD

**Issue by XhmikosR** [appveyor/website#245]
So, instead of the images, @FeodorFitsner you will be able to customize the testimonials from your Twitter account, their number etc.

See https://dev.twitter.com/web/embedded-timelines/collection.

In order I can get started I need you to create a collection and share the html code.

You can see an example on https://www.bootstrapcdn.com/

**Comment by XhmikosR** [comment]
You can see an example on https://www.bootstrapcdn.com/

**Comment by FeodorFitsner** [comment]
Is it possible to embed them as a separate items (not like a single list inside iframe like in your example), say 3 in a row at the bottom of the home page and then randomly choose them on each reload?

**Comment by XhmikosR** [comment]
I'm not aware of a solution to randomize them.

For what Twitter collections support please look at the docs  https://dev.twitter.com/web/embedded-timelines/collection

**Comment by XhmikosR** [comment]
And https://support.twitter.com/articles/20169914#
