### ISSUE TITLE
API Docs Don't List Build Status Values

### ISSUE THREAD

**Issue by sshaw** [appveyor/website#256]
https://www.appveyor.com/docs/api/projects-builds/

There are various status properties but what can their values be? `queued` and `success` are shown in the examples but what's the complete set?

**Comment by IlyaFinkelshteyn** [comment]
Hi Skye,

let me answer here as I am not sure right how to nicely fit it into doc:

`queued`
`running`
`success`
`failed`
`cancelling`
`cancelled`

Ilya.

**Comment by sshaw** [comment]
Great, thanks!
