### ISSUE TITLE
Badges for invalid repos?

### ISSUE THREAD

**Issue by Arcanemagus** [appveyor/website#280]
It seems that instead of a badge for an invalid/unknown repo, a JSON failure message is returned:

* Good: [![AppVeyor](https://ci.appveyor.com/api/projects/status/github/AtomLinter/linter-eslint?svg=true)](https://github.com/AtomLinter/linter-eslint)
* Invalid: [![AppVeyor](https://ci.appveyor.com/api/projects/status/github/AtomLinter/atom-minimap-linter?svg=true)](https://github.com/AtomLinter/atom-minimap-linter) (`{"message":"Project not found or access denied."}`)

Can an "invalid badge" be returned instead? For example CircleCI and Travis-CI both support this:

* Good: [![CircleCI](https://circleci.com/gh/AtomLinter/linter-eslint.svg?style=shield)](https://circleci.com/gh/AtomLinter/linter-eslint)[![Build Status](https://travis-ci.org/AtomLinter/linter-eslint.svg)](https://travis-ci.org/AtomLinter/linter-eslint)
* Invalid: [![CircleCI](https://circleci.com/gh/AtomLinter/atom-linter-pug.svg?style=shield)](https://circleci.com/gh/AtomLinter/atom-linter-pug)[![Build Status](https://travis-ci.org/AtomLinter/atom-minimap-linter.svg)](https://travis-ci.org/AtomLinter/atom-minimap-linter)

**Comment by FeodorFitsner** [comment]
Will take a look.

**Comment by FeodorFitsner** [comment]
Closing this issue in favor https://github.com/appveyor/ci/issues/1468
