### ISSUE TITLE
download-file.md curl isnt in default PATH

### ISSUE THREAD

**Issue by jayvdb** [appveyor/website#290]
See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found

**Comment by FeodorFitsner** [comment]
Could you please elaborate what you mean?

**Comment by jayvdb** [comment]
https://github.com/appveyor/website/blob/master/src/docs/how-to/download-file.md says
"Curl (curl.exe) comes bundled with Git and is therefore also available on the build workers."

which is true, but the user needs to add `C:\Program Files\Git\mingw64\bin` to `PATH`.
That needs explaining.

**Comment by FeodorFitsner** [comment]
Fixed: https://www.appveyor.com/docs/how-to/download-file/#curl
