### ISSUE TITLE
Clarification for deploying IIS website using Agent deployment

### ISSUE THREAD

**Issue by TheBeardedLlama** [appveyor/website#389]
Can you please update [the deploy IIS website settings](https://github.com/appveyor/website/blob/master/src/docs/deployment/agent.md) to clearly state which are required and which are optional

I'm trying to deploy and I just get a `Unable to find any application to deploy. Please ensure that artifacts you want to deploy are named, and required deployment provider settings are set.`
The error message is not helpful at all. I'd rather not have to set all properties just to get it working.

Also it'd be good to know what the required *location* is for some of these settings. i.e. what needs to be in the UI and what can be either there or the yml file.

**Comment by IlyaFinkelshteyn** [comment]
This error is not about luck of some specific setting. Artifact name (deployment name, not a file name) to deploy is coded inside setting. E.g. if you have `<artifact_name>.deploy_website: true`, then build from which you are trying to deploy should have artifact with this specific `artifact_name`.
If this does not shed enough light, please share your Deployment environment settings screenshot (**please remove environment access key and any confidential info from it**) and link to the build.

**Comment by TheBeardedLlama** [comment]
Thank you for the response Ilya.


The docs should say what is required, what is optional and what are the defaults. This should be clear and unequivocal. Currently it is not.
In addition, it would seem that the location where some of these settings are declared matters, so the docs should say what settings can only be in UI and which ones can exist in UI or yml. 

With regards to my specific issue, the deployment worked when I moved all the settings in the UI from the yml, hence the edit to add the setting location as something that should be in the docs.

Does that make sense?

**Comment by IlyaFinkelshteyn** [comment]
I agree that documentation is far from ideal. We are trying to constantly improve it and also compensate luck of it with a fast support. Also our site if open source and if you have an idea how to improve some specific part of it, PR is welcome :)

**Comment by TheBeardedLlama** [comment]
I'd be happy to, but I don't have the required knowledge to do so, hence filing an issue instead of a PR.

As for my specific issue, can you please confirm which settings can only be declared in the UI? I'd rather keep as many settings as possible in the yml.

**Comment by IlyaFinkelshteyn** [comment]
Sorry for confusion. Actually all settings for Environment deployment should be set in UI. Artifact deployment name is a key for each setting. 

What you can do with YAML, is to [overwrite environment variables](https://www.appveyor.com/docs/deployment/environment/) and add [deployment conditions](https://www.appveyor.com/docs/deployment/#conditional-deployment). 

With environment variables you can move a lot of control to YAML (check [this part of doc](https://www.appveyor.com/docs/deployment/agent/#overriding-settings-while-deploying-from-build)). But I would recommend using this only when really needed, because troubleshooting gets more complicated.

**Comment by TheBeardedLlama** [comment]
Oh I see.
That's a bit of a disconnect from the rest of the configuration isn't it?
In any case, it explains why my stuff was not working :smile: 
Feel free to close the issue although it'd be good to get the docs updated :wink:

**Comment by TheBeardedLlama** [comment]
ok, so I'll take that to mean no one is going to be working on the docs...

sigh :disappointed:

**Comment by IlyaFinkelshteyn** [comment]
Sorry, lets keep it open then. I just do not see some single place we could in docs right now. All needed information is already in docs, but I admit that it is a little bit disconnected.

**Comment by TheBeardedLlama** [comment]
If you look at my opening remarks:
"Can you please update the deploy IIS website settings to clearly state which are required and which are optional"
"The docs should say what is required, what is optional and what are the defaults."

That's a good place to start and should be easy enough to do. I can file a separate issue for that if you like.
