### ISSUE TITLE
github deploy example confusing/missleading

### ISSUE THREAD

**Issue by tooomm** [appveyor/website#401]
from https://www.appveyor.com/docs/deployment/github/
>```
>deploy:
>  release: myproduct-v$(appveyor_build_version)
>  description: 'Release description'
>  provider: GitHub
>  auth_token:
>    secure: <your encrypted token> # your encrypted token from GitHub
>  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
>  draft: false
>  prerelease: false
>  on:
>    branch: master                 # release from master branch only
>    appveyor_repo_tag: true        # deploy on tag push only
>```

But the on condition shouldn't work like that regarding https://www.appveyor.com/docs/deployment/#deploy-on-tag-github-and-gitlab-only
>However, please note that branch and appveyor_repo_tag are mutually exclusive. This is because, in the case of tag, it replaces the branch in the webhook content and there is no practical reliable way to recognize from what branch the tag was created. Therefore with this setting deployment will happen only for the master branch:
>
>```
>provider: Environment
>  name: production
>  on:
>    branch: master # only this will work
>    appveyor_repo_tag: true # condition will never be evaluated
>```

Don't know which is right...

**Comment by IlyaFinkelshteyn** [comment]
@tooomm sorry for confusion, this *branch and appveyor_repo_tag are mutually exclusive* is true in case of **annotated** tag. Branch stays in case of regular tag. Will update documentation shortly.

**Comment by tooomm** [comment]
Hmm. What's the difference between a *annotated tag* and a *regular tag*?

**Comment by IlyaFinkelshteyn** [comment]
@tooomm I think people [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and [here](https://stackoverflow.com/questions/11514075/what-is-the-difference-between-an-annotated-and-unannotated-tag) explain that better than me :)

**Comment by tooomm** [comment]
Gotcha and thanks for the links!

Will review the changes and leave a comment again 👍
