### ISSUE TITLE
Deployment page should list hosts names as they are and not uppercased

### ISSUE THREAD

**Issue by roozbehid-ic** [appveyor/website#407]
In deployment page, hostnames are all upper case.
It would help if you can show them how they are and preserve the cases.
these hostnames are reported from our Appveyor Agent application.

**Comment by IlyaFinkelshteyn** [comment]
Could you provide more details? Is it about hostnames reported in the deployment log?

**Comment by IlyaFinkelshteyn** [comment]
AppVeyor displays what [Environment.MachineName](https://msdn.microsoft.com/en-us/library/system.environment.machinename(v=vs.110).aspx) returns on the Agent machine. Please check what `[System.Environment]::MachineName` in PowerShell to verify.

I am closing this ticket. Feel free to reopen if I am not correct.
