### ISSUE TITLE
Document PowerShell Version

### ISSUE THREAD

**Issue by kjin** [appveyor/website#408]
I can't find concrete details about the PowerShell version that I should expect in my builds. I expected it to be here https://www.appveyor.com/docs/build-environment/ but didn't find what I wanted... so I eventually ended up running a dummy CI build to report the PowerShell version manually. Could this be documented in the website docs?

**Comment by IlyaFinkelshteyn** [comment]
We will update it, when we have Windows PowerShell and PowerShell core side-by-side after next update.

**Comment by FeodorFitsner** [comment]
Related issue: https://github.com/appveyor/ci/issues/2021
