### ISSUE TITLE
Menus styles are broken

### ISSUE THREAD

**Issue by FeodorFitsner** [appveyor/website#42]
After merging latest PRs styles are broken:

![image](https://cloud.githubusercontent.com/assets/5041459/5785002/9544d5dc-9d86-11e4-90c9-5efdee66f4ce.png)

**Comment by XhmikosR** [comment]
That is not broken. That is intentional. It's the active class.

**Comment by FeodorFitsner** [comment]
But it looks different than the original. I'll do a new website to test
changes.


-Feodor

**Comment by XhmikosR** [comment]
You mean the sidebar? Because that is intentional too; now it's using proper Foundation markup.

**Comment by XhmikosR** [comment]
Hint for the future: you should check out the PRs locally and see the changes before merging; this workflow you followed here is bad...

Anyway, let me know what exactly is that you think is broken.

**Comment by FeodorFitsner** [comment]
You're right - my bad, sorry for wasting your time.

I've setup Staging website http://appveyor-staging.azurewebsites.net/ which
is getting published from "staging" branch - now we can work together.
Target your PRs to that branch.


-Feodor

**Comment by XhmikosR** [comment]
Can you revert the revert? Or even force push after skipping the rollback patch, it shouldn't matter since only we 2 seem to currently use the repo.

**Comment by FeodorFitsner** [comment]
Sure, I reverted it on "staging" branch. And live site: http://appveyor-staging.azurewebsites.net/docs

**Comment by FeodorFitsner** [comment]
I'm going to work on a new version of home page next week.

**Comment by XhmikosR** [comment]
You should just force push the master branch. Having the rollback patch in git doesn't server any purpose.

**Comment by XhmikosR** [comment]
Your master should be like  https://github.com/XhmikosR/website/commits/master

**Comment by XhmikosR** [comment]
OK for the new webpage, most of this stuff will stay.

PS. If you switch to Bootstrap I can certainly do more changes easily.

**Comment by FeodorFitsner** [comment]
Every push to "master" is automatically published to a live website :)


-Feodor

**Comment by XhmikosR** [comment]
Yeah, but the rollback here is bogus ;) We can use the staging branch from now on after you do the force push of master.

**Comment by FeodorFitsner** [comment]
OK, how to properly do that?


-Feodor

**Comment by XhmikosR** [comment]
Not sure how you can do via cmd, but basically you need to do a `git reset --hard 40cd4bb2d1529b8bc6f4ee04f0dc3d35f547821b` while you are the master branch. Then after you make sure that everything is OK you force push.

**Comment by XhmikosR** [comment]
git reset --hard 40cd4bb2d1529b8bc6f4ee04f0dc3d35f547821b
git push --force-with-lease  "origin" master:master

**Comment by FeodorFitsner** [comment]
I'm going to reset up to this one:
https://github.com/appveyor/website/commit/c1df27ffe4d62d33280e0676d4321dc3e1a86807


-Feodor

**Comment by XhmikosR** [comment]
Why is that? I thought you agreed with the other changes.

**Comment by FeodorFitsner** [comment]
Those changes after c# code cleanup commit changed website look. I missed
it that time.


-Feodor

**Comment by FeodorFitsner** [comment]
I wanna go through all style changes next week when I have time and before
doing a new home page.




-Feodor

**Comment by XhmikosR** [comment]
And what are we supposed to do if you reset to that? It's way cleaner to tell me exactly what you don't like and let me fix it than doing unneeded blind reverts.

If you reset to the patch you say, then any other patches, useful or not will be removed. And that's bad because I have useful changes.

**Comment by XhmikosR** [comment]
There are no style changes. The fact that you didn't use proper markup doesn't justify it :p

Anyway, again, it's much easier to tell me exactly what you don't like than resetting to the patch you said.

**Comment by FeodorFitsner** [comment]
Sure, before some recent changes sidebar and top menu became looking
differently. At the top is how it looks with all PRs applied - at the
bottom is how it should look:

[image: Inline image 1]


-Feodor

**Comment by XhmikosR** [comment]
I don't see any image.

**Comment by XhmikosR** [comment]
Cherry pick this  https://github.com/XhmikosR/website/commit/df739e0ea208381f22749c0812f7dd6776655263 after you reset the master to 40cd4bb2d1529b8bc6f4ee04f0dc3d35f547821b. It should be what you want, I guess and we won't lose any of the other changes.

**Comment by XhmikosR** [comment]
Or check out my master branch, test it locally and if you are OK with that, force push it to your upstream/master.

**Comment by FeodorFitsner** [comment]
Updated post, so you can see the image.

**Comment by XhmikosR** [comment]
It's exactly what I told you. You used random sidebar markup, not the one Foundation supports and I added the active class, which makes totally sense.

Anyway,  https://github.com/appveyor/website/issues/42#issuecomment-70335884 do that, and should be OK.

**Comment by FeodorFitsner** [comment]
OK, checked your master branch. Left side bar looks good though top menu highlight color is different (i guess it's standard one from Foundation). Compare:

![image](https://cloud.githubusercontent.com/assets/5041459/5785843/e771d940-9d90-11e4-8b8e-4e62ba20e81a.png)

**Comment by FeodorFitsner** [comment]
When top menu is OK I think it makes sense to revert the revert and then you just send PR with sidebar and top bar fixes?

**Comment by XhmikosR** [comment]
That is the default Foundation on hover background. Sure, I can change it, but I believe the new one is better; has better contrast.

**Comment by XhmikosR** [comment]
Anyway, I'll add it back. Just reset the master to the patch I mention above and I'll make a PR.

**Comment by XhmikosR** [comment]
Patch updated to use the same hover background as before.

**Comment by FeodorFitsner** [comment]
Reverted. Go ahead with PR.

**Comment by XhmikosR** [comment]
This can be closed.

Also, delete and create the staging branch from the current master. Or reset it.

**Comment by XhmikosR** [comment]
@FeodorFitsner: you can close this.
