### ISSUE TITLE
API does not return correct content and error code

### ISSUE THREAD

**Issue by henryruhs** [appveyor/website#424]
Hello,

I found an issue with the following routes:

```
https://ci.appveyor.com/api
```

```
https://ci.appveyor.com/api/projects/invalid/invalid/invalid
```

1. It does not return `JSON` and ignores `'Content-Type': 'application/json'`
1. It returns status code 200 instead of 404

**Comment by redaxmedia** [comment]
Is there a chance to see any update here?
