### ISSUE TITLE
JDK 10 Support in Appveyor for Windows

### ISSUE THREAD

**Issue by cheenamalhotra** [appveyor/website#460]
Appveyor for Windows currently supports only till JDK 9, documentation [here](https://www.appveyor.com/docs/build-environment/#java).

While, Appveyor for Linux also installs JDK 10 (openJDK 10) as mentioned [here](https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#pre-installed-software).

**Comment by FeodorFitsner** [comment]
Yep, it's going to be in the nearest update: https://github.com/appveyor/ci/issues/2195
