### ISSUE TITLE
Quick start `Install-Product...` fails on Linux images

### ISSUE THREAD

**Issue by jacobq** [appveyor/website#468]
[Quick start](https://github.com/appveyor/website/blob/master/src/docs/lang/nodejs-iojs.md#quick-start) suggests using the following line to install the latest Node.js version:
`ps: Install-Product node $env:nodejs_version`
However, this appears to fail on Linux (tried with `Ubuntu` image) with the error message:
`Install-Product : The term 'Install-Product' is not recognized as the name of a cmdlet, function, script file, or operable program.`

Is this a problem with the documentation or the image? (Or am I just doing something wrong?)

**Comment by jacobq** [comment]
Seems like one needs to use something else like `nvm use 8` or `stack: node 8` on Linux VMs.

**Comment by IlyaFinkelshteyn** [comment]
Correct, [here](https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#configuring-language-stack) we described approach for Linux build. We are working on making documentation and experience more straightforward and unified.

**Comment by jacobq** [comment]
> We are working on making documentation and experience more straightforward and unified.
OK. I guess what surprised/confused me most was that (1) this simple, recommended, and unqualified (nothing on the page suggests that it is just for Windows images) configuration does not work (making me think I must be doing something wrong), and (2) some other powershell stuff seems to work on Linux images but not this one.

**Comment by FeodorFitsner** [comment]
Closing the issue in favor of https://github.com/appveyor/website/issues/474

**Comment by jacobq** [comment]
Oops, looks like it didn't close, so I'll do it. Just wanted to make sure that the doc issues are being tracked / worked on somewhere.
