### ISSUE TITLE
Can svg or other badges be for specific build image as well?

### ISSUE THREAD

**Issue by CatGirlsAreLife** [appveyor/website#490]
So like for example I already use a table for things on the builds like:

Master: [status badge for master]
Current: [status badge for whatever the current build is]

But what if I want 2 other collum s for "vs2017", and "vs2017 preview" to display how my build works on those versions of vs2017 for example. So basically something like "?image=Visual%20Studio%202017" for stable vs job and "?image=Visual%20Studio%202017%20Preview" for the preview image of vs2017.

Not sure if that is possible to do or if it is possible why it is not documented.

**Comment by IlyaFinkelshteyn** [comment]
Yes, we plan to do that. I am closing this as a duplication to https://github.com/appveyor/ci/issues/1805

**Comment by CatGirlsAreLife** [comment]
After thinking about it I think it would be best to simply make it like:
\<Badge urls base with / without branch\>/\<system if not windows\>/\<image name/job name>?svg=true&\<svg text changes as needed\>
