### ISSUE TITLE
Incorrectly named YAML files

### ISSUE THREAD

**Issue by AvdN** [appveyor/website#546]
Appveyor, by default, doesn't use the  ``.yaml`` file extension on YAML files, although this is the officially recommended file extension ( http://yaml.org/faq.html, this has been so at least since Sept 24th, 2006 according to the Wayback Machine ). AFAIK the only excuse for using `.yml` is if you are working on an 8.3 filesystem.

In the documentation, and on the web site, all references to the file format should be to ``YAML`` and not to ``.yml``. 

E.g. you can already specify a correctly named YAML file using the ``Custom configuration .yml file name``. This filed should be named: ``Custom configuration YAML file name``

Of course it  would be even better to also change the defaults for loaded files to use ``.yaml`` extensions. E.g. ``appveyor.yaml``, but given the amount of incorrectly named files out there, that should be implemented to fall back to   ``appveyor.yml``. If such correction is considered, the names that are tried for loading might as well be ``appeveyor.yaml``, ``.appeyor.yaml``, ``appveyor.yml``, so you can automatically hide the file without special Appveyor project setup.

**Comment by IlyaFinkelshteyn** [comment]
Sure, we can do that. Closing in favor of https://github.com/appveyor/ci/issues/2718, as CO` pepo is the right place for issues like this.
