### ISSUE TITLE
forgot password not work

### ISSUE THREAD

**Issue by ArgoZhang** [appveyor/website#629]
I think maybe cause by captcha.
![pwd](http://images.sdgxgz.com/appveyor_pwd2.png "link")

_Originally posted by @ArgoZhang in https://github.com/appveyor/website/issues/622#issuecomment-496336067_

**Comment by ArgoZhang** [comment]
it's not working for me right now. how about others?

**Comment by FeodorFitsner** [comment]
I've just checked from Safari on macOS Sierra and it works just fine.

**Comment by ArgoZhang** [comment]
could you drop a sceenshot for me？ mac chrome is not work too. maybe because i am request from china！

**Comment by ArgoZhang** [comment]
it done! i'am sure caused by request from china. I have changed my password use shadowsocks jump to korea.
