### ISSUE TITLE
how to avoid generate artifacts on dev branch？

### ISSUE THREAD

**Issue by ArgoZhang** [appveyor/website#630]
i do not want to generate the artifact on dev branch. how to config in UI or in `appveyor.yml` file

**Comment by OwenMcDonnell** [comment]
Can you please create a ticket on our [support forum](https://help.appveyor.com/home) as this repo is for documentation issues only. 
And do the same for any other support issues you've posted here.

**Comment by ArgoZhang** [comment]
i can't post any issue in support forum. i tried many times before.

**Comment by ArgoZhang** [comment]
i guess the support forum use a same lib(Verify Human) with [forgot-password](https://ci.appveyor.com/forgot-password).  i can't click the **Create** button like **send password** button in forgot-password page. #629

**Comment by OwenMcDonnell** [comment]
Have you tried a different email address?
