### ISSUE TITLE
No markdown in appveyor-yml.md

### ISSUE THREAD

**Issue by vors** [appveyor/website#66]
I tried to fix typos in http://www.appveyor.com/docs/appveyor-yml so I open https://github.com/appveyor/website/blob/master/NJekyll/site/docs/appveyor-yml.md by the link at the end of the page.
But there is no markdown, it just include everything from JS.
How to contribute to this page?

**Comment by FeodorFitsner** [comment]
It's here, the gist: https://gist.github.com/FeodorFitsner/0bd366055d8865251366

**Comment by vors** [comment]
Indeed. that's a smart solution for syntax highlighting on the site!

**Comment by vors** [comment]
There is no way to send a pull request for gist, so I just observe that comment on line 12 (`# You can use {branch} to, for example`) duplicate comment on next line and probably should be removed.

**Comment by FeodorFitsner** [comment]
Fixed. Thanks!


-Feodor
