### ISSUE TITLE
Typo issue in case sensitive variable value APPVEYOR_REPO_PROVIDER

### ISSUE THREAD

**Issue by PalashBansal** [appveyor/website#678]
On page- https://www.appveyor.com/docs/deployment/github/ (website/src/docs/deployment/github.md)
In line- "Note that the provider name `GitHub` is case sensitive (e.g. not `Github`)."
It should be **gitHub** not **GitHub**
As its case sensitive, it might be major typo mistake.
I believe this is for environment variable "APPVEYOR_REPO_PROVIDER"
"gitHub" value is also mentioned at https://www.appveyor.com/docs/environment-variables/
To confirm, i ran a batch script with "set" command in a PR in 1 of the repo i am working on and it showed- "APPVEYOR_REPO_PROVIDER=gitHub" (refer- https://ci.appveyor.com/project/ihhub/fheroes2/builds/28386537/job/q2lk77j8bu7dadv4)
As i am using this env var value in my batch script, case sensitivity doesn't make any difference.
But appveyor website mentioned "case-sensitive", so raising this issue.

Please confirm, so i can open a PR fixing this.

**Comment by FeodorFitsner** [comment]
There is no mistake, actually. Deployment provider name should be `GitHub`, but the value of `APPVEYOR_REPO_PROVIDER` is `gitHub`.

**Comment by PalashBansal** [comment]
Thanks for the clarification. Closing :)
