### ISSUE TITLE
software pre-installed Qt 2019 path

### ISSUE THREAD

**Issue by theshadowx** [appveyor/website#693]
There is an issue in the path for Qt related to msvc 2019
as the following screenshot shows, it path used for msvc 2019 is the same for 2017 : 
![Selection_001](https://user-images.githubusercontent.com/976569/71030053-f31a4580-2110-11ea-9818-9c8b47dd1b54.jpg)

**Comment by FeodorFitsner** [comment]
Thanks for pointing that out. It's not an error, but there are no Qt builds for VS 2019, so we deploy VS 2017 builds which are binary-compatible with VS 2019.

**Comment by theshadowx** [comment]
ok, then it's better to mention it, as it's confusing.
