### ISSUE TITLE
BYOC documentation clarity, multiple cloud build environments and offline status

### ISSUE THREAD

**Issue by HariSekhon** [appveyor/website#709]
Hi,

I've been testing BYOC functionality but it exits immediately after setting up in a docker container.

```
Reading Host Agent authorization token from the existing cloud.

Ensure build worker image is available for AppVeyor projects
AppVeyor build worker image 'Linux' already exists.

Installing AppVeyor Host Agent
OS: Linux
Host Agent is already installed
7.0.2546

The script successfully completed in 00:00:07.

Next steps:
 - Optionally review build environment 3247bb2f0aad at https://ci.appveyor.com/build-clouds/812
 - To start building on this computer select Linux build worker image and 3247bb2f0aad build cloud on AppVeyor project settings or in appveyor.yml:

build_cloud: 3247bb2f0aad
image: Linux


PS /pwd> root@3247bb2f0aad:/pwd#
root@3247bb2f0aad:/pwd#
```

You can reproduce exactly what I am doing using this script:

https://github.com/HariSekhon/DevOps-Bash-tools/blob/master/appveyor_byoc_debian.sh

(it leverages several other adjacent scripts to install powershell, appveyor module, debian dependency packages etc so it's easier if you just git clone and then run it).

The agent appears offline shortly after install in the cloud builds page:

https://ci.appveyor.com/build-clouds

Also, it would be helpful if we didn't have to specify a single cloud build environment but could specify to use any one of several available environments that match criteria, eg. Linux.

Additionally, because I am running this in a container the hostname from which the cloud name is defined is temporary, it there something we could do to just use any cloud environment that has Linux agent from any cloud environment?

This bit around having to name a specific build_cloud seems like something that needs clarifying, as well as why the agent is offline.

The script I've provided should enable you to reproduce it exactly, all you need is `APPVEYOR_TOKEN` in the environment and docker installed and it'll do everything else.

One other minor issue I noticed, the terminal gets messed up and resets to the top without clearing and then starts overwriting the existing output, making it hard to see (I've had to hold enter to clear it while it's running so new information is printed further down to see what's going on, at which point it exists and the pending newlines race down the screen so I then have to scroll up - it's a minor annoyance but would be good if it could be fixed).

Thanks

Hari

**Comment by FeodorFitsner** [comment]
Will take a look. Where `pwsh` is getting from? Does `debian:9` already contain it?

**Comment by HariSekhon** [comment]
Yes the script I mentioned uses the official install method from Microsoft for powershell. You can simply run it, it'll run a debian docker container, install powershell, the appveyor module and run it to reproduce the error I showed above.

**Comment by FeodorFitsner** [comment]
AppVeyor Host Agent is installed as systemd service. AFAIK systemd is not available in Docker containers - could it be the problem? So, if you want to have Host Agent inside container I'd expect something like `docker run <image-with-host-agent> <path-to-host-agent-executable>`.

**Comment by HariSekhon** [comment]
Yes I should have noticed that, looks like starting it myself gets it up and running, thanks!
