### ISSUE TITLE
Multi-line PowerShell script example is wrong

### ISSUE THREAD

**Issue by sschuberth** [appveyor/website#77]
The example [To add multi-line PowerShell script covering an entire event](http://www.appveyor.com/docs/build-configuration) does not work for me. It says

    on_success: |
      if($true)
      {
        Write-Host "Success"
      }

But if done like this the code is executed as "cmd", not as "ps", and fails. I tried to guess the right syntax and used `on_success: ps |` in the first line which did not work either. After looking at [libgit2's appveyor.yml file](https://github.com/libgit2/libgit2/blob/master/appveyor.yml) I found that

    on_success:
      - ps: |
      if($true)
      {
        Write-Host "Success"
      }

works. It even works when adding other script lines before or after, very similar to the help page's next example that uses `- ps: >-`, but the above does not require the extra line breaks.

So I'm a bit confused. Why would I want to use `- ps: >-` if `- ps: |` works the same and does not require the extra line breaks?

**Comment by FeodorFitsner** [comment]
It's been fixed. Thank you!

**Comment by sschuberth** [comment]
Thanks! But below the example it still says "The extra line breaks used above are required", though there are no extra line breaks anymore now :-)

**Comment by FeodorFitsner** [comment]
Good catch! It's been removed.
