### ISSUE TITLE
Documented method for clearing build cache via REST does not work

### ISSUE THREAD

**Issue by randombit** [appveyor/website#776]
The docs claim issuing a `DELETE` to `https://ci.appveyor.com/api/projects/{accountName}/{projectSlug}/buildcache` will remove the cache.

```
$ export APPVEYOR_TOKEN="v2.xtcy..."
$ curl -X DELETE -H "Authorization: Bearer $APPVEYOR_TOKEN" 'https://ci.appveyor.com/api/projects/randombit/botan/buildcache'
{"message":"Account cannot be accessed with current authentication method."}
```

The token seems to be correct since if I modify it I instead get a response `{"message":"Authorization required"}`

**Comment by FeodorFitsner** [comment]
Enable both API authentication methods on https://ci.appveyor.com/account/randombit/security page.
