### ISSUE TITLE
Java version problem when following SonarQube blog post

### ISSUE THREAD

**Issue by ceddlyburge** [appveyor/website#779]
Hi there

I recently received [an issue about an incompatible java version](https://github.com/ceddlyburge/sonarqube-nemo-on-appveyor/issues/5) on the companion repository to the [blog post about SonarQube](https://www.appveyor.com/blog/2016/12/23/sonarqube/) that I wrote on your website.

I'm happy to update the blog post with the suggestion in the issue, but I'm wondering if you might want to do it a different way (by having a different default version of Java for example).

Please let me know and I'll update the post accordingly.

Thanks, Cedd

**Comment by FeodorFitsner** [comment]
Main concern here is breaking existing builds. I think we could replace default Java version on Visual Studio 2019, not sure about others. In my opinion it's safer to update the blog post with the instructions on how to set Java version which is good for SonarQube other than assuming the default Java version in VM is compatible with it.

**Comment by ceddlyburge** [comment]
Hi Feodor, no worries, I'll just update the blog post. Cheers, Cedd
