### ISSUE TITLE
Feature request: document scheduled builds better

### ISSUE THREAD

**Issue by richelbilderbeek** [appveyor/website#796]
Dear AppVeyor,

I am happy to find out that AppVeyor supports scheduled builds ( https://www.appveyor.com/docs/build-configuration/#scheduled-builds ) as that will ensure the quality of my work.

Currently, however, there are no examples how to actually add it to an `appveyor.yml` script. Sure, how to set the `cron` has multiple links, but one example of a minimal `appveyor.yml` script that runs a scheduled job is missing.

I hope this will be added.

Cheers, Richel Bilderbeek

**Comment by FeodorFitsner** [comment]
Currently scheduled builds can be configured via UI only.

**Comment by richelbilderbeek** [comment]
Great! I close this one, with a follow-up question at #797
