### ISSUE TITLE
AppVeyor Server releases outdated

### ISSUE THREAD

**Issue by DoLearnWhileAlive** [appveyor/website#813]
Are there any plans for updating the AppVeyor releases on the website again?
https://www.appveyor.com/releases

Also this site https://www.appveyor.com/self-hosted is stating the very old release [7.0.2942](https://www.appveyor.com/releases/7.0.2942/) from 2020 as latest version.

At least the chocolatey package update automatism is depending on this.
New users could also believe AppVeyor Server is not maintained anymore and starting with an old buggy version will be frustrating until finding out in the [appveyor/ci issues](https://github.com/appveyor/ci/issues) that there are already fixed versions.

**Comment by FeodorFitsner** [comment]
This is a valid note! It's been just updated: https://www.appveyor.com/self-hosted/
