### ISSUE TITLE
Provide options for custom moderators in organizations

### ISSUE THREAD

**Issue by OrkoHunter** [appveyor/website#82]
We've been working on a repository under the [NetworkX](https://github.com/networkx) organization. It seems that only owners has the privilege of moderating builds. This seems to be causing a little problem for us as because the owners are sometimes unavailable to do the job.

If I am correct, Travis-CI allows collaborators to restart/cancel builds.

readthedocs.org also provides an option for the owner to assign moderators for the project.

It would really be a great feature if AppVeyor incorporates any/all of the above two features.

Thank you.

**Comment by FeodorFitsner** [comment]
You can create a new role in AppVeyor and give it required permissions.

**Comment by OrkoHunter** [comment]
Didn't see that. This helps http://www.appveyor.com/docs/team-setup.
