### ISSUE TITLE
What is the build timeout appveyor.yml configuration option

### ISSUE THREAD

**Issue by joachimmetz** [appveyor/website#846]
https://github.com/appveyor/website/blob/master/src/docs/build-configuration.md references a "Build timeout". What is the appveyor.yml configuration option for this? For context I want to lower the value to 15 mins from the configuration.

**Comment by FeodorFitsner** [comment]
Build timeout can be set on UI only (General tab of project settings).

**Comment by joachimmetz** [comment]
@FeodorFitsner thanks for the insights. I'll use the UI then.
